//
// Created by Benson on 2025/10/29.
//

#ifndef INC_408_DATASTRUCTURE_ARRAY_QUEUE_HPP
#define INC_408_DATASTRUCTURE_ARRAY_QUEUE_HPP


class array_queue {};


#endif //INC_408_DATASTRUCTURE_ARRAY_QUEUE_HPP